using System.Globalization;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;

// 사용법: dotnet run --project tools/HolidayData.Generator -- <출력경로.cs>
// 출력경로 미지정 시 기본값으로 src/KoreanHolidays/Generated/HolidayData.g.cs 사용.

string outputPath = args.Length > 0
    ? args[0]
    : Path.Combine("src", "KoreanHolidays", "Generated", "HolidayData.g.cs");

string dataDir = Path.Combine(AppContext.BaseDirectory, "data");
var files = Directory.GetFiles(dataDir, "*.json")
    .Where(f => Regex.IsMatch(Path.GetFileNameWithoutExtension(f), @"^\d{4}$"))
    .OrderBy(f => f, StringComparer.Ordinal)
    .ToList();

if (files.Count == 0)
    throw new InvalidOperationException($"데이터 파일을 찾을 수 없습니다: {dataDir}");

var substituteRegex = new Regex(@"^대체공휴일\((?<base>.+)\)$");

var rows = new List<(DateOnly Date, string Name, bool IsSub, string? SubFor)>();
foreach (var file in files)
{
    using var doc = JsonDocument.Parse(File.ReadAllText(file, Encoding.UTF8));
    foreach (var dateProp in doc.RootElement.EnumerateObject())
    {
        var date = DateOnly.ParseExact(dateProp.Name, "yyyy-MM-dd", CultureInfo.InvariantCulture);
        foreach (var nameEl in dateProp.Value.EnumerateArray())
        {
            var name = nameEl.GetString()!;
            var m = substituteRegex.Match(name);
            if (m.Success)
                rows.Add((date, name, true, m.Groups["base"].Value));
            else
                rows.Add((date, name, false, null));
        }
    }
}

// 날짜 오름차순 (같은 날은 원본 배열 순서 유지 — OrderBy는 안정 정렬).
var sorted = rows.OrderBy(r => r.Date).ToList();
int minYear = sorted.Min(r => r.Date.Year);
int maxYear = sorted.Max(r => r.Date.Year);

var sb = new StringBuilder();
sb.AppendLine("// <auto-generated/>");
sb.AppendLine("// 원본: https://github.com/hyunbinseo/holidays-kr (월력요항 기반)");
sb.AppendLine("// 이 파일은 tools/HolidayData.Generator 가 생성합니다. 직접 편집하지 마세요.");
sb.AppendLine("#nullable enable");
sb.AppendLine();
sb.AppendLine("using System;");
sb.AppendLine();
sb.AppendLine("namespace KoreanHolidays;");
sb.AppendLine();
sb.AppendLine("internal static partial class HolidayData");
sb.AppendLine("{");
sb.AppendLine($"    internal const int MinYear = {minYear};");
sb.AppendLine($"    internal const int MaxYear = {maxYear};");
sb.AppendLine();
sb.AppendLine("    internal static Holiday[] CreateAll() =>");
sb.AppendLine("    [");
foreach (var r in sorted)
{
    string subFor = r.SubFor is null ? "null" : Quote(r.SubFor);
    sb.AppendLine(
        $"        new() {{ Date = new DateOnly({r.Date.Year}, {r.Date.Month}, {r.Date.Day}), " +
        $"Name = {Quote(r.Name)}, IsSubstitute = {(r.IsSub ? "true" : "false")}, SubstituteFor = {subFor} }},");
}
sb.AppendLine("    ];");
sb.AppendLine("}");

Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(outputPath))!);
File.WriteAllText(outputPath, sb.ToString().ReplaceLineEndings("\n"), new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
Console.WriteLine($"생성 완료: {outputPath} ({sorted.Count} entries, {minYear}~{maxYear})");

static string Quote(string s) => "\"" + s.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
